import { api } from '~/utils/api'
import Head from 'next/head'

import { useUser } from '@clerk/nextjs'

import { type NextPage } from 'next'

const ProfilePage: NextPage = () => {
  const { isLoaded: userLoaded } = useUser()
  // Start fetching asap so it's ready (stored in cache) once the user is loaded
  api.posts.getAll.useQuery()

  // return empty div if user isn't loaded yet (it happens fast so no point to show spinner)
  if (!userLoaded) return <div />

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">Profile view</main>
    </>
  )
}

export default ProfilePage
